# nome da rotina a ser executada
name: Go
# quando e onde a rotina será executada
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# define as tarefas que serão executadas nesta rotina
jobs:
  # define a tarefa a ser executada, no caso, a tarefa de build
  build:
    # define onde a tarefa de build será executada, caso em um ambiente ubuntu
    runs-on: ubuntu-latest
    # passos para executar a tarefa de build
    steps:
      # define o repositorio em que o ambiente será configurado
      # no caso, será utilizado o repositório do "actions" com nome "checkout" na versão "v3"
      # isso permitirá utilizar o uso de funções do GitHub Actions no nosso ambiente
      - uses: actions/checkout@v3
      # passo de configuração do Go no ambiente
      - name: Set up Go
        # este passo se utilizará o repositório, que contem todos os códigos
        # necessários para configuração do Go no ambiente
        uses: actions/setup-go@v4
        # indica a versão do Go que desejamos
        with:
          go-version: "1.20"
      # este passo fará a compilação do código Go
      - name: Build
        # executa um comando em nosso ambiente
        run: go build -v ./...
      # este passo executará os testes do código Go
      - name: Test
        run: go test -v ./...
